### ISSUE TITLE
Pypi is not updated

### ISSUE THREAD

**Issue by Mosrod** [101t/bigbluebutton-api-python#6]
I have installed the pypi and have realized that it was not the latest version of bigbluebutton-api-python as shown here. Would you be able to update the pypi as the older version doesn't work?

**Comment by BrutalBirdie** [comment]
That's right!
I just manually fixed this error
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import bigbluebutton_api_python
  File "/root/.local/lib/python3.5/site-packages/bigbluebutton_api_python/__init__.py", line 3, in <module>
    from .bigbluebutton import BigBlueButton
  File "/root/.local/lib/python3.5/site-packages/bigbluebutton_api_python/bigbluebutton.py", line 16, in <module>
    from .util import UrlBuilder
  File "/root/.local/lib/python3.5/site-packages/bigbluebutton_api_python/util/__init__.py", line 2, in <module>
    from .urlbuilder import UrlBuilder
  File "/root/.local/lib/python3.5/site-packages/bigbluebutton_api_python/util/urlbuilder.py", line 9, in <module>
    from urllib.request import quote_plus
ImportError: cannot import name 'quote_plus'
```
by replacing 
```diff
- from urllib.request import quote_plus
+ from urllib.parse import quote_plus
```
And now I wanted to create a PR and noticed that util/urlbuilder is not the same file :D

**Comment by BrutalBirdie** [comment]
But wait a second ...
https://pypi.org/project/bigbluebutton-api-python/ > Homage links to https://github.com/yunkaiwang/bigbluebutton-api-python a fork of this Project.

The work is up-2-date but still installing version 0.0.9 has the old version 🤔

**Comment by Mosrod** [comment]
🤔 Are you able to take control of the pypi repository?

**Comment by 101t** [comment]
@Mosrod , actually I can't, @yunkaiwang has control on pypi.

**Comment by yunkaiwang** [comment]
I've uploaded a new version 0.0.11 on pypi with the problem fixed.
